---
Parameters:
  IAMUserLoginProfilePassword:
    Type: String
Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: !Ref IAMUserLoginProfilePassword
        PasswordResetRequired: True