---
Parameters:
  IAMUserLoginProfilePassword:
    Type: String
    NoEcho: True
    Default: b@dP@$sW0rD
Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: !Ref IAMUserLoginProfilePassword
        PasswordResetRequired: True