---
Resources:
  IAMUser:
    Type: AWS::IAM::User
    Properties: 
      LoginProfile: 
        Password: '{{resolve:secretsmanager:/iam/user/loginprofile_password:SecretString:password}}'
        PasswordResetRequired: True