---
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSSandboxChannel:
    Type: AWS::Pinpoint::APNSSandboxChannel
    Properties:
      TokenKey: b@d0@u7H70K3n
      ApplicationId: !Ref PinpointApp
