---
Parameters:
  PinpointAPNSSandboxChannelPrivateKey:
    Type: String
    NoEcho: True
    Default: b@dP@$sW0rD
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSSandboxChannel:
    Type: AWS::Pinpoint::APNSSandboxChannel
    Properties:
      PrivateKey: !Ref PinpointAPNSSandboxChannelPrivateKey
      ApplicationId: !Ref PinpointApp
