---
Parameters:
  OpsWorksStackCustomCookbooksSourcePassword:
    Type: String
    NoEcho: True
    Default: b@dP@$sW0rD
Resources:
  OpsWorksStack:
    Type: AWS::OpsWorks::Stack
    Properties:
      CustomCookbooksSource:
        Password: !Ref OpsWorksStackCustomCookbooksSourcePassword
        Username: admin
      DefaultInstanceProfileArn: arn:aws:iam::123456789012:instance-profile/MyProfile-foobar
      Name: foobar
      ServiceRoleArn: arn:aws:iam::123456789012:role/MyRole-foobar
