---
Resources:
  OpsWorksStack:
    Type: AWS::OpsWorks::Stack
    Properties:
      CustomCookbooksSource:
        Password: b@dP@$sW0rD
        Username: admin
      DefaultInstanceProfileArn: arn:aws:iam::123456789012:instance-profile/MyProfile-foobar
      Name: foobar
      ServiceRoleArn: arn:aws:iam::123456789012:role/MyRole-foobar
