AllCops:
  TargetRubyVersion: 2.5
Layout/IndentHeredoc:
  Enabled: false

# not a bad notion except when you are actually trying to select things that are not(something)
Style/InverseMethods:
  Enabled: false
