AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'

Style/IfUnlessModifier:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 19

Style/StderrPuts:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false
  #PreferredName: something_that_describes_the_actual_exception_or_error

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/ClassLength:
  Max: 115

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
