AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Enabled: false

Security/Eval:
  Enabled: false

Metrics/AbcSize:
  Max: 16

Lint/RescueException:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Max: 50
