AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/**/*'

Performance/RegexpMatch:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 16

Security/Eval:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Lint/RescueException:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Lint/StringConversionInInterpolation:
  Enabled: false

Style/Next:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
