FROM ruby:2.5-alpine3.9@sha256:f33782620b363575ad95d19d0f0f07f7d197e9ccfee51f20df39dd33d408cdb4

COPY . /

RUN apk add --update build-base \
    curl \
    git

RUN gem install bundler
RUN gem install rubocop
RUN bundle install
