---
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: single-node
      DBName: foobar
      MasterUserPassword: '{{resolve:secretsmanager:/redshift/cluster/masteruserpassword:SecretString:password}}'
      MasterUsername: admin
      NodeType: dc2.large
