---
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: single-node
      DBName: foobar
      MasterUserPassword: b@dP@$sW0rD
      MasterUsername: admin
      NodeType: dc2.large
