---
Parameters:
  RedshiftClusterMasterUserPassword:
    Type: String
    NoEcho: True
    Default: b@dP@$sW0rD
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: single-node
      DBName: foobar
      MasterUserPassword: !Ref RedshiftClusterMasterUserPassword
      MasterUsername: admin
      NodeType: dc2.large
