---
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: single-node
      DBName: foobar
      MasterUserPassword: '{{resolve:ssm:UnsecureSecretString:1}}'
      MasterUsername: admin
      NodeType: dc2.large
