---
Parameters:
  RedshiftClusterMasterUserPassword:
    Type: String
Resources:
  RedshiftCluster:
    Type: AWS::Redshift::Cluster
    Properties:
      ClusterType: single-node
      DBName: foobar
      MasterUserPassword: !Ref RedshiftClusterMasterUserPassword
      MasterUsername: admin
      NodeType: dc2.large
