---
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSVoipSandboxChannel:
    Type: AWS::Pinpoint::APNSVoipSandboxChannel
    Properties:
      PrivateKey: '{{resolve:ssm-secure:SecureSecretString:1}}'
      ApplicationId: !Ref PinpointApp
