---
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSVoipSandboxChannel:
    Type: AWS::Pinpoint::APNSVoipSandboxChannel
    Properties:
      TokenKey: '{{resolve:secretsmanager:/pinpoint/app/tokenkey:SecretString:password}}'
      ApplicationId: !Ref PinpointApp
