---
Parameters:
  PinpointAPNSVoipSandboxChannelPrivateKey:
    Type: String
    NoEcho: True
    Default: b@d0@u7H70K3n
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSVoipSandboxChannel:
    Type: AWS::Pinpoint::APNSVoipSandboxChannel
    Properties:
      PrivateKey: !Ref PinpointAPNSVoipSandboxChannelPrivateKey
      ApplicationId: !Ref PinpointApp
