---
Parameters:
  CognitoUserPoolMfaConfiguration4:
    Type: String
    Default: 'OFF'
    Description: Must be values of  either 'OFF | ON | OPTIONAL'

  CognitoUserPoolMfaConfiguration5:
    Type: String
    Default: 'Off'
    Description: Must be values of  either 'OFF | ON | OPTIONAL'

  CognitoUserPoolMfaConfiguration6:
    Type: String
    Default: 'off'
    Description: Must be values of  either 'OFF | ON | OPTIONAL'


Resources:
  # When specifying MfaConfiguration as ON or OFF, those values MUST be wrapped in quotes.
  # They are reserved YAML key words and CFN will fail to deploy stack otherwise.
  CognitoUserPool4:
    Type: AWS::Cognito::UserPool
    Properties:
      MfaConfiguration: !Ref CognitoUserPoolMfaConfiguration4
      # The below property is required when specifying ON/OPTIONAL for MfaConfiguration
      SmsConfiguration:
        SnsCallerArn: 'arn:aws:iam::12345678910:role/service-role/test-cognito-SMS-Role'

  CognitoUserPool5:
    Type: AWS::Cognito::UserPool
    Properties:
      MfaConfiguration: !Ref CognitoUserPoolMfaConfiguration5
      # The below property is required when specifying ON/OPTIONAL for MfaConfiguration
      SmsConfiguration:
        SnsCallerArn: 'arn:aws:iam::12345678910:role/service-role/test-cognito-SMS-Role'

  CognitoUserPool6:
    Type: AWS::Cognito::UserPool
    Properties:
      MfaConfiguration: !Ref CognitoUserPoolMfaConfiguration6
      # The below property is required when specifying ON/OPTIONAL for MfaConfiguration
      SmsConfiguration:
        SnsCallerArn: 'arn:aws:iam::12345678910:role/service-role/test-cognito-SMS-Role'

