---
Parameters:
  AmazonMQBrokerUsersPassword:
    Type: String
Resources:
  AmazonMQBroker:
    Type: AWS::AmazonMQ::Broker
    Properties:
      AutoMinorVersionUpgrade: true
      BrokerName: MyAmazonMQBroker
      DeploymentMode: SINGLE_INSTANCE
      EngineType: ACTIVEMQ
      EngineVersion: "5.15.0"
      HostInstanceType: mq.t2.micro
      PubliclyAccessible: false
      Users:
        - Password: !Ref AmazonMQBrokerUsersPassword
          Username: admin
