---
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSChannel:
    Type: AWS::Pinpoint::APNSChannel
    Properties:
      PrivateKey: '{{resolve:secretsmanager:/pinpoint/app/privatekey:SecretString:password}}'
      ApplicationId: !Ref PinpointApp
