---
AWSTemplateFormatVersion: 2010-09-09
Description: Creates EMR cluster with misconfigured at rest encryption.

Parameters:
  JobFlowRoleName:
    Type: String
    Description: Name of role to use for JobFlowRole.
    Default: EMR_EC2_DefaultRole
  ServiceRoleName:
    Type: String
    Description: Name of EMR service role.
    Default: EMR_DefaultRole
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID where the cluster should be launched.

Resources:
  EMRClusterWithMisconfiguredAtRestEncryption:
    Type: AWS::EMR::Cluster
    Properties:
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m1.medium
          Market: ON_DEMAND
          Name: MasterInstanceGroup
        CoreInstanceGroup:
          InstanceCount: 1
          InstanceType: m1.medium
          Market: ON_DEMAND
          Name: CoreInstanceGroup
        Ec2SubnetId: !Ref SubnetId
      JobFlowRole: !Ref JobFlowRoleName
      Name: EMRClusterWithMisconfiguredAtRestEncryption
      ReleaseLabel: emr-5.29.0
      SecurityConfiguration: !Ref EMRSecurityConfigWithMisconfiguredAtRestEncryption
      ServiceRole: !Ref ServiceRoleName
  EMRSecurityConfigWithMisconfiguredAtRestEncryption:
    Type: AWS::EMR::SecurityConfiguration
    Properties:
      SecurityConfiguration:
        EncryptionConfiguration:
          EnableAtRestEncryption: true
          EnableInTransitEncryption: true
          AtRestEncryptionConfiguration:
            WrongKey: true
          InTransitEncryptionConfiguration:
            TLSCertificateConfiguration:
              CertificateProviderType: PEM