---
Parameters:
  OpsWorksAppAppSourcePassword:
    Type: String
Resources:
  OpsWorksApp:
    Type: AWS::OpsWorks::App
    Properties:
      Name: foobar
      AppSource: 
        Type: git
        Url: git://github.com/foo/bar.git
        Revision: v1.0.0
        Password: !Ref OpsWorksAppAppSourcePassword
        Username: admin   
      StackId: Stack-Foo
      Type: static
