---
Resources:
  OpsWorksApp:
    Type: AWS::OpsWorks::App
    Properties:
      Name: foobar
      SslConfiguration:
        Certificate: Certificate-Foo
        Chain: Chain-Bar
        PrivateKey: '{{resolve:secretsmanager:/opsworks/app/sslconfiguration_privatekey:SecretString:password}}'
      StackId: Stack-Foo
      Type: static
