---
Resources:
  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      AuthenticationConfiguration: 
        AllowedIPRange: 10.0.0.0/0
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/master
      Authentication: GITHUB_HMAC
      TargetPipeline: foobar-pipeline
      TargetAction: foo-source
      Name: foobar
      TargetPipelineVersion: 1
