---
Parameters:
  CodePipelineWebhookAuthenticationConfigurationSecretToken:
    Type: String
Resources:
  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      AuthenticationConfiguration: 
        SecretToken: !Ref CodePipelineWebhookAuthenticationConfigurationSecretToken
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/master
      Authentication: GITHUB_HMAC
      TargetPipeline: foobar-pipeline
      TargetAction: foo-source
      Name: foobar
      TargetPipelineVersion: 1
