---
Resources:
  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      AuthenticationConfiguration: 
        SecretToken: b@d0$3cR3T70K3n
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/master
      Authentication: GITHUB_HMAC
      TargetPipeline: foobar-pipeline
      TargetAction: foo-source
      Name: foobar
      TargetPipelineVersion: 1
