---
Resources:
  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      AuthenticationConfiguration: 
        SecretToken: '{{resolve:ssm-secure:SecureSecretString:1}}'
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/master
      Authentication: GITHUB_HMAC
      TargetPipeline: foobar-pipeline
      TargetAction: foo-source
      Name: foobar
      TargetPipelineVersion: 1
