---
Resources:
  CodePipelineWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      AuthenticationConfiguration: 
        SecretToken: '{{resolve:secretsmanager:/codepipeline/webhook/authenticationconfiguration_secrettoken:SecretString:password}}'
      Filters:
        - JsonPath: $.ref
          MatchEquals: refs/heads/master
      Authentication: GITHUB_HMAC
      TargetPipeline: foobar-pipeline
      TargetAction: foo-source
      Name: foobar
      TargetPipelineVersion: 1
