---
Parameters:
  ManagedBlockchainMemberMemberConfigurationMemberFrameworkConfigurationMemberFabricConfigurationAdminPassword:
    Type: String
    NoEcho: True
Resources:
  ManagedBlockchainMember:
    Type: AWS::ManagedBlockchain::Member
    Properties:
      MemberConfiguration:
        Name: foobar
        MemberFrameworkConfiguration:
          MemberFabricConfiguration:
            AdminUsername: admin
            AdminPassword: !Ref ManagedBlockchainMemberMemberConfigurationMemberFrameworkConfigurationMemberFabricConfigurationAdminPassword
