---
Resources:
  ManagedBlockchainMember:
    Type: AWS::ManagedBlockchain::Member
    Properties:
      MemberConfiguration:
        Name: foobar
        MemberFrameworkConfiguration:
          MemberFabricConfiguration:
            AdminUsername: admin
            AdminPassword: b@dP@$sW0rD
