---
Resources:
  ManagedBlockchainMember:
    Type: AWS::ManagedBlockchain::Member
    Properties:
      MemberConfiguration:
        Name: foobar
        MemberFrameworkConfiguration:
          MemberFabricConfiguration:
            AdminUsername: admin
            AdminPassword: '{{resolve:secretsmanager:/managedblockchain/member/memberconfiguration_memberframeworkconfiguration_memberfabricconfiguration_adminpassword:SecretString:password}}'
