---
Resources:
  ManagedBlockchainMember:
    Type: AWS::ManagedBlockchain::Member
    Properties:
      MemberConfiguration:
        Name: foobar
        MemberFrameworkConfiguration:
          MemberFabricConfiguration:
            AdminUsername: admin
            AdminPassword: '{{resolve:ssm-secure:SecureSecretString:1}}'
