---
Resources:

  GenericGroup:
    Type: AWS::IAM::Group
    Properties: 
      GroupName: GenericGroup

  InlinePolicyPass:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: WildcardResourcePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: 
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
            Resource: "arn:aws:s3:::*"
          -
            Effect: Allow
            Action:
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
            Resource: "*"
          -
            Effect: Allow
            Action: "iam:PassRole"
            Resource: "arn:aws:s3:::*"
      Groups:
        - !Ref GenericGroup