---
Resources:

  GenericGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: GenericGroup

  ManagedPolicyPass1:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
            Resource: "arn:aws:s3:::*"

  ManagedPolicyPass2:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action:
              - "s3:ListBucket"
              - "s3:GetBucketLocation"
            Resource: "*"

  ManagedPolicyPass3:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Action: "iam:PassRole"
            Resource: "arn:aws:s3:::*"
      Groups:
        - !Ref GenericGroup

  ManagedPolicyPass4:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Deny
            Action: "iam:PassRole"
            Resource: "*"