---
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: "default"
  myNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC
  myNetworkAclEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: "10.0.0.0/16"
      Egress: false
      NetworkAclId: !Ref 'myNetworkAcl'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: 1000
  myNetworkAclEntry2:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      CidrBlock: "10.0.0.0/16"
      Egress: false
      NetworkAclId: !Ref 'myNetworkAcl'
      Protocol: '-1'
      RuleAction: allow
      RuleNumber: 2000
