---
AWSTemplateFormatVersion: 2010-09-09

Resources:
  SecureGameLiftFleet:
    Type: AWS::GameLift::Fleet
    Properties:
      EC2InboundPermissions:
        - FromPort: 22
          IpRange: 10.1.0.0/24
          Protocol: TCP
          ToPort: 22
        - FromPort: 1122
          IpRange: 10.1.0.0/24
          Protocol: TCP
          ToPort: 1122
        - FromPort: 10623
          IpRange: 10.1.0.0/24
          Protocol: TCP
          ToPort: 10623
      EC2InstanceType: t2.micro
      Name: InsecureGameLiftFleet
