---
Parameters:
  DBClusterMasterUserPassword:
    Type: String
    NoEcho: True
    Default: b@dP@$sW0rD
Resources:
  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DeletionProtection: True
      Engine: aurora-mysql
      MasterUserPassword: !Ref DBClusterMasterUserPassword
      MasterUsername: admin
      Port: 3306
