---
Resources:
  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DeletionProtection: True
      Engine: aurora-mysql
      MasterUserPassword: '{{resolve:ssm-secure:SecureSecretString:1}}'
      MasterUsername: admin
      Port: 3306
