---
Resources:
  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DeletionProtection: True
      Engine: aurora-mysql
      MasterUserPassword: '{{resolve:secretsmanager:/rds/db_cluster/masteruserpassword:SecretString:password}}'
      MasterUsername: admin
      Port: 3306
