---
Resources:
  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DeletionProtection: True
      Engine: aurora-mysql
      MasterUserPassword: b@dP@$sW0rD
      MasterUsername: admin
      Port: 3306
