---
Parameters:
  ElastiCacheReplicationGroupAuthToken:
    Type: String
Resources:
  ElastiCacheReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AuthToken: !Ref ElastiCacheReplicationGroupAuthToken
      CacheNodeType: cache.m5.large
      CacheSubnetGroupName: subnet-foobar
      Engine: redis
      EngineVersion: '5.0.0'
      NumCacheClusters: 2
      ReplicationGroupDescription: foobar
      SecurityGroupIds:
        - sg-foobar
      TransitEncryptionEnabled: True
