---
Resources:
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      EventSourceToken: b@d70K3n
      FunctionName: foobar
      Principal: foo.amazonaws.com
