---
Resources:
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      EventSourceToken: '{{resolve:secretsmanager:/lambda/permission/eventsourcetoken:SecretString:password}}'
      FunctionName: foobar
      Principal: foo.amazonaws.com
