---
Resources:
  RDSDBInstanceWithNoDeletionProtection:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.m5.large
      Engine: mysql
  RDSDBInstanceWithDeletionProtectionDisabled:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.m5.large
      Engine: mysql
      DeletionProtection: False
  Aurora:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.m5.large
      Engine: aurora
