---
Resources:
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '100'
      DBInstanceClass: db.m5.large
      Engine: mysql
      MasterUserPassword: '{{resolve:secretsmanager:/rds/db_instance/masteruserpassword:SecretString:password}}'
      MasterUsername: '{{resolve:secretsmanager:/rds/db_instance/masterusername:SecretString:username}}'
