---
Parameters:
  RDSDBInstanceMasterUserPassword:
    Type: String
    NoEcho: true
    Default: b@dP@$sW0rD
Resources:
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '100'
      DBInstanceClass: db.m5.large
      Engine: mysql
      MasterUserPassword: !Ref RDSDBInstanceMasterUserPassword
      MasterUsername: admin
