---
Resources:
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '100'
      DBInstanceClass: db.m5.large
      Engine: mysql
      MasterUserPassword: b@dP@$sW0rD
      MasterUsername: admin
