---
Resources:
  KinesisFirehoseDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties: 
      DeliveryStreamName: foobar
      DeliveryStreamType: DirectPut
      SplunkDestinationConfiguration:
        HECEndpoint: String
        HECEndpointType: https://splunk.aws.id.foobar:8888
        HECToken: '{{resolve:secretsmanager:/kinesisfirehose/deliverystream/splunkdestinationconfiguration_hectoken:SecretString:password}}'
        S3Configuration: 
          BucketARN: arn:aws:s3:::foobar-bucket
          BufferingHints: 
            IntervalInSeconds: 60
            SizeInMBs: 1
          CompressionFormat: GZIP
          RoleARN: arn:aws:iam::123456789012:role/KinesisFirehose-S3Configuration-foobar