---
Parameters:
  KmsKeyId:
    Type: String
    Default: arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012
Resources:
  DeliveryStream1:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamEncryptionConfigurationInput:
        KeyARN: !Ref KmsKeyId
        KeyType: CUSTOMER_MANAGED_CMK
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: arn:aws:s3:::foobar-bucket
        RoleARN: arn:aws:iam::123456789012:role/KinesisFirehose-foobar
