---
Resources:
  DeliveryStream1:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamEncryptionConfigurationInput:
        KeyType:
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: arn:aws:s3:::foobar-bucket
        RoleARN: arn:aws:iam::123456789012:role/KinesisFirehose-foobar

  DeliveryStream2:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamEncryptionConfigurationInput:
        KeyType: AWS_OWNED_CMK
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: arn:aws:s3:::foobar-bucket
        RoleARN: arn:aws:iam::123456789012:role/KinesisFirehose-foobar

  DeliveryStream3:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamEncryptionConfigurationInput:
        KeyARN: arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012
        KeyType: CUSTOMER_MANAGED_CMK
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: arn:aws:s3:::foobar-bucket
        RoleARN: arn:aws:iam::123456789012:role/KinesisFirehose-foobar
