---
Resources:
  ApiGatewayMethod1:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: AWS_IAM

  ApiGatewayMethod2:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: CUSTOM

  ApiGatewayMethod3:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: COGNITO_USER_POOLS