---
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: IPv6

  SecurityGroupInlineRules1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allow http to web servers
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          Description: Allow http inbound

  SecurityGroupInlineRules2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allow http to web servers
      SecurityGroupEgress:
        - Description: Allow http outbound
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
  
  SecurityGroupExternalRules:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: Allow http to web servers
  SecurityGroupIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Properties:
      Description: Allow HTTP inbound
      GroupId: !Ref SecurityGroupExternalRules
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
  SecurityGroupEgress:
    Type: 'AWS::EC2::SecurityGroupEgress'
    Properties:
      GroupId: !Ref SecurityGroupExternalRules
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      Description: Allow HTTP outbound