---
Parameters:
  DocDBDBClusterMasterUserPassword:
    Type: String
    NoEcho: True
Resources:
  DocDBDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      Port: 27017
      DBClusterIdentifier: foobar
      MasterUserPassword: !Ref DocDBDBClusterMasterUserPassword
      MasterUsername: admin
