---
Resources:
  DocDBDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      Port: 27017
      DBClusterIdentifier: foobar
      MasterUserPassword: '{{resolve:secretsmanager:/docdb/db_cluster/masteruserpassword:SecretString:password}}'
      MasterUsername: admin
