---
Resources:
  DocDBDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      Port: 27017
      DBClusterIdentifier: foobar
      MasterUserPassword: '{{resolve:ssm:UnsecureSecretString:1}}'
      MasterUsername: admin
