---
Resources:
  DocDBDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      Port: 27017
      DBClusterIdentifier: foobar
      MasterUserPassword: b@dP@$sW0rD
      MasterUsername: admin
  