---
Resources:
  BatchJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      ContainerProperties:
        Memory: 512
        Privileged: 'False'
        Vcpus: 1
        Image: amazon/amazon-ecs-agent
