---
name: github-action

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/github-action.yml
      - action.yml
      - github-action/**

jobs:
  e2e:
    name: Action E2E test
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@master
      - name: Simple test
        uses: stelligent/cfn_nag@master
        with:
          input_path: github-action/tests
      - name: Test not showing suppression
        uses: stelligent/cfn_nag@master
        with:
          input_path: github-action/tests
          extra_args: ''
      - name: Test with JSON output
        uses: stelligent/cfn_nag@master
        with:
          input_path: github-action/tests
          extra_args: -o json
      - name: Test multiple extra args
        uses: stelligent/cfn_nag@master
        with:
          input_path: github-action/tests
          extra_args: -o json --template-pattern clean
      - name: Test with SARIF output
        id: sarif
        uses: stelligent/cfn_nag@master
        with:
          input_path: github-action/tests
          extra_args: -o sarif
          output_path: cfn_nag.sarif
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: cfn_nag.sarif
