---
Parameters:
  PinpointAPNSVoipChannelTokenKey:
    Type: String
    NoEcho: True
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSVoipChannel:
    Type: AWS::Pinpoint::APNSVoipChannel
    Properties:
      TokenKey: !Ref PinpointAPNSVoipChannelTokenKey
      ApplicationId: !Ref PinpointApp
