---
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSVoipChannel:
    Type: AWS::Pinpoint::APNSVoipChannel
    Properties:
      TokenKey: '{{resolve:ssm:UnsecureSecretString:1}}'
      ApplicationId: !Ref PinpointApp
