---
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSVoipChannel:
    Type: AWS::Pinpoint::APNSVoipChannel
    Properties:
      PrivateKey: '{{resolve:ssm-secure:SecureSecretString:1}}'
      ApplicationId: !Ref PinpointApp
