---
Parameters:
  PinpointAPNSVoipChannelPrivateKey:
    Type: String
    NoEcho: True
Resources:
  PinpointApp:
    Type: AWS::Pinpoint::App
    Properties:
      Name: foobar
  PinpointAPNSVoipChannel:
    Type: AWS::Pinpoint::APNSVoipChannel
    Properties:
      PrivateKey: !Ref PinpointAPNSVoipChannelPrivateKey
      ApplicationId: !Ref PinpointApp
